websites = {
    'instagram': 'https://www.instagram.com/',
    'google': 'https://www.google.com/',
    'youtube': 'https://www.youtube.com/',
    'facebook': 'https://www.facebook.com/',
    'twitter': 'https://twitter.com/',
    'linkedin': 'https://www.linkedin.com/',
    'pinterest': 'https://www.pinterest.com/',
    'reddit': 'https://www.reddit.com/',
    'tumblr': 'https://www.tumblr.com/',
    'whatsapp': 'https://www.whatsapp.com/',
    'amazon': 'https://www.amazon.com/',
    'ebay': 'https://www.ebay.com/',
    'netflix': 'https://www.netflix.com/',
    'spotify': 'https://www.spotify.com/',
    'twitch': 'https://www.twitch.tv/',
    'wikipedia': 'https://www.wikipedia.org/',
    'microsoft': 'https://www.microsoft.com/',
    'apple': 'https://www.apple.com/',
    'adobe': 'https://www.adobe.com/',
    'cnn': 'https://edition.cnn.com/',
    'yahoo': 'https://www.yahoo.com/',
    'wordpress': 'https://wordpress.com/',
    'github': 'https://github.com/',
    'stack overflow': 'https://stackoverflow.com/',
    'quora': 'https://www.quora.com/',
    'bbc': 'https://www.bbc.co.uk/',
    'nytimes': 'https://www.nytimes.com/',
    'craigslist': 'https://www.craigslist.org/',
    'imdb': 'https://www.imdb.com/',
    'paypal': 'https://www.paypal.com/',
    'walmart': 'https://www.walmart.com/',
    'target': 'https://www.target.com/',
    'etsy': 'https://www.etsy.com/',
    'buzzfeed': 'https://www.buzzfeed.com/',
    'weather': 'https://www.weather.com/',
    'webmd': 'https://www.webmd.com/',
    'forbes': 'https://www.forbes.com/',
    'huffpost': 'https://www.huffpost.com/',
    'cnet': 'https://www.cnet.com/',
    'usatoday': 'https://www.usatoday.com/',
    'nasa': 'https://www.nasa.gov/',
    'nationalgeographic': 'https://www.nationalgeographic.com/',
    'bbcnews': 'https://www.bbc.com/news',
    'espn': 'https://www.espn.com/',
    'time': 'https://time.com/',
    'techcrunch': 'https://techcrunch.com/',
    'engadget': 'https://www.engadget.com/',
    'mashable': 'https://mashable.com/',
    'lifehacker': 'https://lifehacker.com/',
    'businessinsider': 'https://www.businessinsider.com/',
    'wired': 'https://www.wired.com/',
    'theverge': 'https://www.theverge.com/',
    'cnbc': 'https://www.cnbc.com/',
    'pcgamer': 'https://www.pcgamer.com/',
    'gizmodo': 'https://gizmodo.com/',
    'bbc sport': 'https://www.bbc.co.uk/sport',
    'espn': 'https://www.espn.com/',
    'bleacher report': 'https://www.bleacherreport.com/',
    'healthline': 'https://www.healthline.com/',
    'mayo clinic': 'https://www.mayoclinic.org/',
    'medlineplus': 'https://medlineplus.gov/',
    'rottentomatoes': 'https://www.rottentomatoes.com/',
    'metacritic': 'https://www.metacritic.com/',
    'imdb': 'https://www.imdb.com/',
    'allrecipes': 'https://www.allrecipes.com/',
    'epicurious': 'https://www.epicurious.com/',
    'genius': 'https://genius.com/',
    'last.fm': 'https://www.last.fm/',
    'soundcloud': 'https://soundcloud.com/',
    'paramount pictures': 'https://www.paramount.com/',
    'universal pictures': 'https://www.universalpictures.com/',
    '20th century studios': 'https://www.20thcenturystudios.com/',
    'warner bros': 'https://www.warnerbros.com/',
    'sony pictures': 'https://www.sonypictures.com/',
    'disney': 'https://www.disney.com/',
    'techcrunch': 'https://techcrunch.com/',
    'the verge': 'https://www.theverge.com/',
    'mashable': 'https://mashable.com/',
    'gizmodo': 'https://gizmodo.com/',
    'lifehacker': 'https://lifehacker.com/',
    'engadget': 'https://www.engadget.com/',
    'ars technica': 'https://arstechnica.com/',
    'venturebeat': 'https://venturebeat.com/',
    'android authority': 'https://www.androidauthority.com/',
    'macrumors': 'https://www.macrumors.com/',
    'the register': 'https://www.theregister.com/',
    'android central': 'https://www.androidcentral.com/',
    'anandtech': 'https://www.anandtech.com/',
    'xda developers': 'https://www.xda-developers.com/',
    'tom\'s hardware': 'https://www.tomshardware.com/',
    'the next web': 'https://thenextweb.com/',
    'techradar': 'https://www.techradar.com/',
}
